### ISSUE TITLE
"Could not evaluate key path"

### ISSUE THREAD

**Issue by sunshinenoptimism** [apoch8000/WeatherWalls#1]
![48166053-6AFD-499A-B497-1CE6A7F3D9A4](https://user-images.githubusercontent.com/71730446/106773635-48642f80-660f-11eb-9913-630abf753072.png)
![21398FF4-9374-4C7A-B77F-895E6FB347C6](https://user-images.githubusercontent.com/71730446/106773656-4d28e380-660f-11eb-8cf7-8b698bd2bc3c.png)

**Comment by Firefox6** [comment]
issue fixed in 2.4.4
